apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dp5nil5vn-java-springboot
  janus-idp.io/tekton: dp5nil5vn-java-springboot
  backstage.io/kubernetes-id: dp5nil5vn-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dp5nil5vn-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
